### ISSUE TITLE
allow handling multiple topics in a single worker

### ISSUE THREAD

**Issue by dan-amoroso** [Dansvidania/camunda-worker#1]
allow handling multiple topics in a single worker by implementing a library function with the following signature or similar

```worker::run_topic_handlers(worker_id: &str, engine: &Engine, topic_handlers: Vec<(topic: &str, handler: F)>```

**Comment by IdemenB** [comment]
Hi @Dansvidania  and @MilanVasko , I see that you implemented this run_topic_handlers with the following signature:

```
pub async fn run_topic_handlers<F>(config: &Config, handlers: Vec<Handler<F>>)
where
    F: Fn(LockedExternalTaskDto) -> HandlerResult + Send + 'static,
{
```

My problem is that my Rust capabilities is not enough to provide a valid Vec<Handler<F>> into the handlers parameter. I have two basic Handler structs but since the Handler struct has a generic type A, these are considered different types and cannot be put in a vector.

I'll really appreciate if you can give a hint on how to solve this.

![image](https://user-images.githubusercontent.com/56586098/114698288-9be9ac80-9d27-11eb-946a-91b2b9c5a6c5.png)


I tried defining a turbo fish and many other things but to no avail.

**Comment by dan-amoroso** [comment]
Hello @IdemenB 

I must admit ignorance here, I do not know what would be the appropriate way to do this. 

I will try to play around with the worker code and see if I can find a work-around... maybe making the Handler type non-generic?

Could you post a minimal version of your code that triggers this error? I would like to reproduce an go from there.

**Comment by IdemenB** [comment]
Thanks for your interest @Dansvidania . Our solution is most probably here, the concept of trait object.

https://doc.rust-lang.org/book/ch17-02-trait-objects.html

I am also continuing working on this very issue, I'll let you know if I manage to take care of this. Once I'm done with this I'll need to face https://github.com/Dansvidania/camunda-worker/issues/11#issue-857571289 which is even more challenging :)

**Comment by IdemenB** [comment]
@Dansvidania , as I'm experimenting and changing the code quite a bit, I've created a different repo here. I've also simplied the handler functions. There are two, one sleeps for 2 seconds and the another sleeps for 3 seconds. When you run this code, it does not compile because although we have two Handler<A> structs, these are in fact two different types cannot be put into a vector.

REPO: https://github.com/IdemenB/camunda_lib_tests/tree/master

**Comment by MilanVasko** [comment]
Hello @IdemenB,

I think the problem here is that Rust treats each function as its own type, preventing them to be stored together in a vector. There are ways around it, though - you can "cast functions down" as explained [here](https://users.rust-lang.org/t/storing-functions-in-a-vector/32104/3). Taking your main.rs, I think adding type annotations like this should work:

```rust
let first_handler: Handler<fn(Task) -> HandlerResult> = Handler {
    topic: "sendJobStartNotificationByMail".to_owned(),
    handler_function: handlers::two_sec_handler,
};

let second_handler: Handler<fn(Task) -> HandlerResult> = Handler {
    topic: "simpleTopic".to_owned(),
    handler_function: handlers::three_sec_handler,
};
```

I also remember working around this by wrapping the functions in a `Box`, but I don't have an example for it ready right now.

**Comment by IdemenB** [comment]
Thanks a lot @MilanVasko , in fact I tried almost for 3 hours to work around this issue by turbo fishing the vector itself in various forms and many type varieties, including "as" statements next to items in the vector and trying some other things. What you suggested is down casting functions and it worked!

What do you think about the trait bound concept here, instead of making a Generic Handler struct? 

The next thing to attack is to be able to call async handler functions (like SQLx crate DB queries) with multiple concurrent handlers spawned through "tokio::spawn(async move { run_topic_handler(&config, handler) });" in async fn run_topic_handlers<F>. There is a seperate issue for this.
